POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
  "title": "His blogs is dope",
  "author": "Alpha person",
  "url": "https://www.alphaurl.com/post",
  "likes": 23
}